### PR TITLE
Update syntex to 0.38

### PR DESCRIPTION
**Pull request by dtolnay**

### CODE REVIEW

**Comment by dtolnay** [comment]
Looks like the Travis build fails because it is not receiving the most recent nightly.

**Comment by dtolnay** [comment]
Or... what? I just did a `rustup update` and got downgraded from 1.12.0-nightly (2ad5ed07f 2016-07-08) to rustc 1.11.0-nightly (801d2682d 2016-07-06). What is going on?

**Comment by tafia** [comment]
rustup worked fine for me

**Comment by dtolnay** [comment]
I ran rustup again and got "upgraded" from 1.12.0-nightly (2ad5ed07f 2016-07-08) to 1.12.0-nightly (5e18b4bad 2016-07-08). In any case, it looks like Travis is now getting 5e18b4bad so this may finally work.

**Pull request merged**
